# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hyperlocal.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hyperlocal.proto',
  package='',
  serialized_pb='\n\x10hyperlocal.proto\"^\n\nHyperlocal\x12\"\n\x07\x63orners\x18\x01 \x03(\x0b\x32\x11.Hyperlocal.Point\x1a,\n\x05Point\x12\x10\n\x08latitude\x18\x01 \x01(\x02\x12\x11\n\tlongitude\x18\x02 \x01(\x02\"Y\n\rHyperlocalSet\x12\x1f\n\nhyperlocal\x18\x01 \x03(\x0b\x32\x0b.Hyperlocal\x12\'\n\x0c\x63\x65nter_point\x18\x02 \x01(\x0b\x32\x11.Hyperlocal.Point')




_HYPERLOCAL_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='Hyperlocal.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude', full_name='Hyperlocal.Point.latitude', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='Hyperlocal.Point.longitude', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=70,
  serialized_end=114,
)

_HYPERLOCAL = _descriptor.Descriptor(
  name='Hyperlocal',
  full_name='Hyperlocal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='corners', full_name='Hyperlocal.corners', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_HYPERLOCAL_POINT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=20,
  serialized_end=114,
)


_HYPERLOCALSET = _descriptor.Descriptor(
  name='HyperlocalSet',
  full_name='HyperlocalSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hyperlocal', full_name='HyperlocalSet.hyperlocal', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='center_point', full_name='HyperlocalSet.center_point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=116,
  serialized_end=205,
)

_HYPERLOCAL_POINT.containing_type = _HYPERLOCAL;
_HYPERLOCAL.fields_by_name['corners'].message_type = _HYPERLOCAL_POINT
_HYPERLOCALSET.fields_by_name['hyperlocal'].message_type = _HYPERLOCAL
_HYPERLOCALSET.fields_by_name['center_point'].message_type = _HYPERLOCAL_POINT
DESCRIPTOR.message_types_by_name['Hyperlocal'] = _HYPERLOCAL
DESCRIPTOR.message_types_by_name['HyperlocalSet'] = _HYPERLOCALSET

class Hyperlocal(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Point(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _HYPERLOCAL_POINT

    # @@protoc_insertion_point(class_scope:Hyperlocal.Point)
  DESCRIPTOR = _HYPERLOCAL

  # @@protoc_insertion_point(class_scope:Hyperlocal)

class HyperlocalSet(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HYPERLOCALSET

  # @@protoc_insertion_point(class_scope:HyperlocalSet)


# @@protoc_insertion_point(module_scope)
